### ISSUE TITLE
Tracking issue for supporting plan chain rules

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaMath/AbstractFFTs.jl#94]
Tracks progress towards supporting plan chain rules. This requires supporting adjoints of plans, and that in turn requires that we create a package for testing FFT plans to give downstream implementations a way of easily testing adjoint functionality.

- [ ] Create an `AbstractFFTsTestUtils.jl` package with the interface tests, and move it into the `JuliaMath` organization (https://github.com/gaurav-arya/AbstractFFTsTestUtils.jl, needs transfer)
- [ ] Add integration testing with `AbstractFFTsTestUtils.jl` in `AbstractFFTs` (#78)
- [ ] Implement adjoints of plans (#67) and add tests in `AbstractFFTsTestUtils.jl` 
- [ ] Implement extra trait functions required for adjoints in downstream packages (FFTW, CUDA, AMD) and test using `AbstractFFTsTestUtils.jl`
- [ ] Implement chain rules of plans via adjoints (currently part of #67, but should be factored out into a separate PR to make sure we only override Zygote's chain rule once we have adjoint support downstream)

**Comment by vpuri3** [comment]
Also https://github.com/JuliaMath/FFTW.jl/pull/273
